/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./../components/Breadcrumb/index.vue')['default'];
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete'];
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb'];
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag'];
    ElCol: typeof import('element-plus/es')['ElCol'];
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElDivider: typeof import('element-plus/es')['ElDivider'];
    ElDrawer: typeof import('element-plus/es')['ElDrawer'];
    ElDropdown: typeof import('element-plus/es')['ElDropdown'];
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElImage: typeof import('element-plus/es')['ElImage'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElOption: typeof import('element-plus/es')['ElOption'];
    ElPagination: typeof import('element-plus/es')['ElPagination'];
    ElPopover: typeof import('element-plus/es')['ElPopover'];
    ElRadio: typeof import('element-plus/es')['ElRadio'];
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton'];
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup'];
    ElRow: typeof import('element-plus/es')['ElRow'];
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
    ElSelect: typeof import('element-plus/es')['ElSelect'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    ElSwitch: typeof import('element-plus/es')['ElSwitch'];
    ElTable: typeof import('element-plus/es')['ElTable'];
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
    ElTag: typeof import('element-plus/es')['ElTag'];
    ElText: typeof import('element-plus/es')['ElText'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    ElUpload: typeof import('element-plus/es')['ElUpload'];
    Gitee: typeof import('./../components/Blog/gitee/index.vue')['default'];
    Github: typeof import('./../components/Blog/github/index.vue')['default'];
    Hamburger: typeof import('./../components/Hamburger/index.vue')['default'];
    Home: typeof import('./../components/Blog/home/index.vue')['default'];
    Pagination: typeof import('./../components/Pagination/index.vue')['default'];
    ParentView: typeof import('./../components/ParentView/index.vue')['default'];
    Password: typeof import('./../components/Password/index.vue')['default'];
    RightToolBar: typeof import('./../components/RightToolBar/index.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Screenfull: typeof import('./../components/Screenfull/index.vue')['default'];
    Settings: typeof import('./../components/Settings/index.vue')['default'];
    SizeSelect: typeof import('./../components/SizeSelect/index.vue')['default'];
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default'];
  }

  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective'];
  }
}
